// realpass display overrides. Existing localization keys and settings identities are retained.
// Adapted English text: Dark Future 2.0 by DarkFortuneTeller, CC BY-SA 4.0.
// https://github.com/DarkFortuneTeller/DarkFuture/blob/2.0-release/localization/en-us/onscreens/darkfuture.json
// Native localization delivery uses the bundled Codeware provider; this adds no external process.
module CyberpunkRealism.Integration
import Codeware.Localization.*

public class CRRealpassLocalization extends ModLocalizationProvider {
  public func GetPackage(language: CName) -> ref<ModLocalizationPackage> {
    if Equals(language, n"en-us") { return new CRRealpassEnglish(); }
    return null;
  }
  public func GetFallback() -> CName { return n"en-us"; }
}

public class CRRealpassEnglish extends ModLocalizationPackage {
  protected func DefineTexts() {
    this.Text("DarkFutureDummyEffectDesc", "Toggling realpass status icons...");
    this.Text("DarkFutureSettingsModName", "realpass");
    this.Text("DarkFutureSettingTutorialsEnabledDesc", "Show one-time tutorials of each mechanic of realpass. These appear contextually during gameplay.");
    this.Text("DarkFutureSettingUpdateMessagesEnabledDesc", "Show a one-time message when realpass is updated to a major new version on an existing save game. (Default: Enabled)");
    this.Text("DarkFutureSettingForceShowUpdateMessageDesc", "In addition to the activation message, shows the latest update message when starting a new game or when loading a save that does not have realpass installed. (Default: Disabled)");
    this.Text("DarkFutureSettingMainSystemEnabled", "Enable realpass");
    this.Text("DarkFutureSettingMainSystemEnabledDesc", "Enables realpass gameplay systems, including the integrated needs and addiction systems. Disabling this setting is for troubleshooting; installed item and menu descriptions may still show realpass. Based on Dark Future 2.0 by DarkFortuneTeller (CC BY-SA 4.0).");
    this.Text("DarkFutureSettingCompatibilityProjectE3HUDDesc", "Updates the appearance of realpass's HUD elements to be visually compatible with Project E3 - HUD. Only enable if Project E3 - HUD is installed.");
    this.Text("DarkFutureSettingCompatibilityProjectE3UIDesc", "Updates the appearance of realpass's Inventory and Skip Time UI elements to be visually compatible with Project E3 - UI. Only enable if Project E3 - UI is installed.");
    this.Text("DarkFutureTutorialNerveTitle", "realpass - Nerve");
    this.Text("DarkFutureTutorialCombinedNeedsTitle", "realpass - Basic Needs");
    this.Text("DarkFutureTutorialInjuryTitle", "realpass - Injury");
    this.Text("DarkFutureTutorialHumanityLossTitle", "realpass - Humanity Loss");
    this.Text("DarkFutureTutorialCyberpsychosisTitle", "realpass - Cyberpsychosis");
    this.Text("DarkFutureTutorialAddictionTitle", "realpass - Addiction");
    this.Text("DarkFutureTutorialActivateTitle", "Welcome to realpass");
    this.Text("DarkFutureTutorialActivateUpdateTitle", "What's New in realpass");
    this.Text("DarkFutureWarningInvalidLanguageSettingTitle", "realpass Error - Invalid Language Settings");
    this.Text("DarkFutureWarningWannabeEdgerunnerTitle", "realpass Warning - Wannabe Edgerunner");
    this.Text("DarkFutureErrorInvalidConfigurationTitle", "realpass Error - Invalid Configuration");
    this.Text("DarkFutureTutorialSleepingInVehiclesTitle", "realpass - Sleeping In Vehicles");
    this.Text("DarkFutureTutorialActivate", "realpass is enabled. Food and drink absorb gradually; eating, drinking, sleeping and relaxing matter. Open the weapon wheel to inspect needs, or the backpack for body status. Customize the experience under realpass in Mod Settings.\n\nBuilt on Dark Future 2.0 by DarkFortuneTeller (CC BY-SA 4.0), with original realpass physiology and integration. Source and credits: https://github.com/natanai/cprealpass");
    this.Text("DarkFutureTutorialActivate_V20", "This realpass build includes shared body simulation, gradual food and drink absorption, recoverable exertion fatigue and clearer backpack body status.\n\nBuilt on Dark Future 2.0 by DarkFortuneTeller (CC BY-SA 4.0), with original realpass physiology and integration. Source and credits: https://github.com/natanai/cprealpass");
    this.Text("DarkFutureWarningInvalidLanguageSetting", "In order for realpass to work correctly, your Subtitles and Interface settings must be set to the same language. To fix this, navigate to Settings -> Language, and set both Subtitles and Interface to the same language.\n\nrealpass will not work correctly until this is fixed. Particularly, Energy will not be restored when sleeping in a bed, and many other interactions throughout the game will not work as intended. As the mod is currently in an invalid state, this message will repeat until the issue is fixed.\n\nThis is a technical limitation of the current capabilities of RedScript. Please refrain from reporting this as a bug, as the mod author is unable to address it. Thank you for your understanding.");
    this.Text("DarkFutureWarningWannabeEdgerunner", "realpass now includes optional Humanity Loss and Cyberpsychosis systems that are tightly integrated with realpass. These features are currently enabled. Wannabe Edgerunner was also detected, which adds similar mechanics.\n\nrealpass's Cyberpsychosis system can be disabled if you would prefer to continue using Wannabe Edgerunner. It is, however, recommended that you leave realpass's Humanity Loss system enabled, as it has a significantly impact on gameplay outside of Cyberpsychosis.\n\nIn order to ensure the best experience, you should either:\n- Keep Wannabe Edgerunner installed, and disable realpass's Cyberpsychosis system (under \"Survival - Humanity Loss and Cyberpsychosis\" in Mod Settings), or,\n- Uninstall Wannabe Edgerunner");
    this.Text("DarkFutureErrorInvalidConfigurationBasicNeedThresholds", "In order for realpass to work correctly, you must correctly configure the Basic Need Penalty Stage Threshold values in Mod Settings:\n\nStage 1 Threshold must be greater than Stage 2 Threshold.\nStage 2 Threshold must be greater than Stage 3 Threshold.\nStage 3 Threshold must be greater than Stage 4 Threshold.\n\nPlease reconfigure these settings, exit the game, and restart. realpass WILL NOT FUNCTION CORRECTLY until this is completed.");
    this.Text("DarkFutureCodex_BasicNeeds_Content", "NUTRITION, HYDRATION, and ENERGY are Basic Needs that measure your overall level of hunger, thirst, and alertness. They deplete as time passes, resulting in status effects that become increasingly severe. They are represented by the three small meters beneath the Stamina meter on the HUD.\n\nHold <Input actionName=\"WeaponWheel\" color=\"Tutorial.InputHint\"></> to open the quick-access menu to view the details of Basic Need status effects currently applied.\n\nNutrition and Hydration are restored by eating and drinking. Energy can be completely restored by sleeping in one of your hideouts. A limited amount of Energy can be restored by sleeping in a vehicle or by consuming caffeinated drinks and narcotics.\n\nLow-quality food and drinks (typically from vending machines) often come with penalties, while high-quality food and drinks may provide bonuses if Nutrition and Hydration are satisfied.\n\nIf your Nerve is low, you may be too nauseous to eat or drink, or too restless to sleep.\n\nNutrition, Hydration, Energy, and the benefits of consumables can be configured in realpass's Mod Settings.");
    this.Text("DarkFutureCodex_Nerve_Content", "NERVE is a Basic Need that represents how calm and collected you are. Losing Nerve will result in negative status effects, and can potentially lead to death. Nerve is represented by the large meter beneath the Stamina meter on the HUD.\n\nHold <Input actionName=\"WeaponWheel\" color=\"Tutorial.InputHint\"></> to open the quick-access menu to view the details of Basic Need status effects currently applied.\n\nCombat or being traced from Quickhacks will cause your Nerve to deplete rapidly. Having low Hydration, Nutrition, or Energy will cause your Nerve to deplete slowly over time.\n\nNerve is restored by engaging in relaxing activities like sleeping in a bed, taking a shower, or dancing. Nerve can also be restored by smoking, drinking alcohol, or using narcotics, but doing so inflicts a range of other negative side effects.\n\nStress kills! Unlike other Basic Needs, if your Nerve reaches 0, you will suffer a fatal heart attack.\n\nNerve, and death from running out of Nerve, can be configured in realpass's Mod Settings.");
    this.Text("DarkFutureCodex_Addiction_Content", "ADDICTION can result from the repeated use of an addictive substance.\n\nYou will experience Withdrawal after enough time has passed since last consuming the substance. Withdrawal will limit your total Nerve until the effect wears off, or until you consume the substance again.\n\nAs you continue to use the substance, your Addiction will become more severe, leading to Withdrawals with lower Nerve limits.\n\nAddiction can only be cured by the passage of time. Addiquit, a consumable purchasable at Medpoint vendors, can help manage Withdrawal effects while trying to cure an Addiction.\n\nAddictions can be configured or disabled in realpass's Mod Settings.");
    this.Text("DarkFutureCodex_Injury_Content", "INJURY is a Condition that represents the lingering effects of physical damage. As it progresses, it reduces Health item effectiveness and how quickly Health regenerates.\n\nThis Condition progresses:\n- When taking damage.\n\nProgresses slower for each point of Armor you have.\n\nInjury is restored by using Trauma Kits. The chance of becoming Injured can be configured or disabled in realpass's Mod Settings.");
    this.Text("DarkFutureCodex_HumanityLoss_Content", "HUMANITY LOSS is a Condition that represents your long-term mental health and connection to the world around you. As it progresses, it delays Nerve loss from combat and while being traced until after the danger has passed, at the cost of limiting the Nerve restored from activities like sleeping and showering. Consumables that restore Nerve continue to provide their full benefit.\n\nThis Condition progresses:\n- When Nerve is lost from combat, being traced.\n- From specific story-related events.\n\nProgresses faster for each point of Cyberware Capacity allocated unless under the effect of an Immunosuppressant.\n\nHumanity Loss is restored by specific story events, as well as once per day from repeatable activities displaying <Image id=\"UIIcon.DarkFutureHumanityLoss\" align=\"bottom\" width=\"75\" height=\"75\"></> like dancing, romantic hangouts, and unique Life Path actions. Endotrisine increases the amount restored from repeatable activities. Story events are unaffected by Endotrisine.\n\nAdvanced Humanity Loss may lead to Cyberpsychosis if your Cyberware Capacity has been exceeded.\n\nHumanity Loss and Cyberpsychosis can be configured or disabled in realpass's Mod Settings.");
    this.Text("DarkFutureCodex_SleepingInVehicles_Content", "You can sleep inside vehicles by pressing and holding <Input actionName=\"DFVehicleSleepAction\" color=\"Tutorial.InputHint\"></>.\n\nTo sleep, the vehicle must be:\n  - Stationary\n  - Not on a road or highway\n  - Enclosed (cannot sleep while on a motorcycle)\n\nBy default, sleeping in a vehicle is less restful than sleeping in a bed. Nerve does not recover, and the amount of Energy you can recover is limited.\n\nNight City's gangs are always on the lookout for an easy target. You may be ambushed while sleeping in your vehicle.\n\nSleeping in vehicles and sleep encounters can be configured in realpass's Mod Settings.");
  }
}
