// Generated from original config/stock-protection.json by Build-StockProtection.ps1.
// Stock identifiers only; no game assets or upstream source bodies copied.
// Provisional coefficients and coarse coverage; combat remains disabled pending validation.
import CyberpunkRealism.Combat.*
public class CRStockProtectionCatalog extends IScriptable {
  public static func Profile(id: Int32) -> ref<CRProtectionProfile> {
    let p: ref<CRProtectionProfile> = new CRProtectionProfile();
    p.resistanceJPerMm2 = -1.0;
    p.durabilityJ = -1.0;
    p.bluntTransferFraction = -1.0;
    if id == 1 {
      p.mapped = true;
      p.torso = true;
      p.resistanceJPerMm2 = 0.02;
      p.durabilityJ = 400.0;
      p.bluntTransferFraction = 0.0;
      return p;
    }
    if id == 2 {
      p.mapped = true;
      p.leftLeg = true;
      p.rightLeg = true;
      p.resistanceJPerMm2 = 0.02;
      p.durabilityJ = 400.0;
      p.bluntTransferFraction = 0.0;
      return p;
    }
    if id == 3 {
      p.mapped = true;
      p.torso = true;
      p.resistanceJPerMm2 = 8.0;
      p.durabilityJ = 6000.0;
      p.bluntTransferFraction = 0.22;
      return p;
    }
    if id == 4 {
      p.mapped = true;
      p.head = true;
      p.torso = true;
      p.leftArm = true;
      p.rightArm = true;
      p.leftLeg = true;
      p.rightLeg = true;
      p.resistanceJPerMm2 = 5.0;
      p.durabilityJ = 5000.0;
      p.bluntTransferFraction = 0.3;
      return p;
    }
    if id == 5 {
      p.mapped = true;
      p.resistanceJPerMm2 = 0.0;
      p.durabilityJ = 1.0;
      p.bluntTransferFraction = 0.0;
      return p;
    }
    return p;
  }
  public static func Resolve(record: TweakDBID) -> ref<CRProtectionProfile> {
    switch record {
      case t"Items.AdvancedBoringPlatingCommon": return CRStockProtectionCatalog.Profile(4);
      case t"Items.AdvancedBoringPlatingCommonPlus": return CRStockProtectionCatalog.Profile(4);
      case t"Items.AdvancedBoringPlatingEpic": return CRStockProtectionCatalog.Profile(4);
      case t"Items.AdvancedBoringPlatingEpicPlus": return CRStockProtectionCatalog.Profile(4);
      case t"Items.AdvancedBoringPlatingLegendary": return CRStockProtectionCatalog.Profile(4);
      case t"Items.AdvancedBoringPlatingLegendaryPlus": return CRStockProtectionCatalog.Profile(4);
      case t"Items.AdvancedBoringPlatingLegendaryPlusPlus": return CRStockProtectionCatalog.Profile(4);
      case t"Items.AdvancedBoringPlatingRare": return CRStockProtectionCatalog.Profile(4);
      case t"Items.AdvancedBoringPlatingRarePlus": return CRStockProtectionCatalog.Profile(4);
      case t"Items.AdvancedBoringPlatingUncommon": return CRStockProtectionCatalog.Profile(4);
      case t"Items.AdvancedBoringPlatingUncommonPlus": return CRStockProtectionCatalog.Profile(4);
      case t"Items.AdvancedKiroshiOpticsBareCommon": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsBareCommonPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsBareEpic": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsBareEpicPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsBareLegendary": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsBareLegendaryPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsBareLegendaryPlusPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsBareRare": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsBareRarePlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsBareUncommon": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsBareUncommonPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsCombinedCommon": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsCombinedCommonPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsCombinedEpic": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsCombinedEpicPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsCombinedLegendary": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsCombinedLegendaryPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsCombinedLegendaryPlusPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsCombinedRare": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsCombinedRarePlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsCombinedUncommon": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsCombinedUncommonPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsHunterCommon": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsHunterCommonPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsHunterEpic": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsHunterEpicPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsHunterLegendary": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsHunterLegendaryPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsHunterLegendaryPlusPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsHunterRare": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsHunterRarePlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsHunterUncommon": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsHunterUncommonPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsPiercingCommon": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsPiercingCommonPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsPiercingEpic": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsPiercingEpicPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsPiercingLegendary": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsPiercingLegendaryPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsPiercingLegendaryPlusPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsPiercingRare": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsPiercingRarePlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsPiercingUncommon": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsPiercingUncommonPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsSensorCommon": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsSensorCommonPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsSensorEpic": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsSensorEpicPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsSensorLegendary": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsSensorLegendaryPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsSensorLegendaryPlusPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsSensorRare": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsSensorRarePlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsSensorUncommonPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsWallhackCommon": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsWallhackCommonPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsWallhackEpic": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsWallhackEpicPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsWallhackLegendary": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsWallhackLegendaryPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsWallhackLegendaryPlusPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsWallhackRare": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsWallhackRarePlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsWallhackUncommon": return CRStockProtectionCatalog.Profile(5);
      case t"Items.AdvancedKiroshiOpticsWallhackUncommonPlus": return CRStockProtectionCatalog.Profile(5);
      case t"Items.Pants_01_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_01_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_01_basic_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_01_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_01_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_01_old_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_01_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_01_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_01_rich_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_02_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_02_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_02_basic_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_02_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_02_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_02_old_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_02_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_02_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_02_rich_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_03_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_03_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_03_basic_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_03_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_03_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_03_old_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_03_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_03_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_03_rich_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_04_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_04_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_04_basic_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_04_basic_04": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_04_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_04_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_04_old_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_04_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_04_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_04_rich_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_05_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_05_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_05_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_05_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_05_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_05_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_06_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_06_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_06_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_06_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_06_old_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_06_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_06_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_07_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_07_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_07_basic_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_07_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_07_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_07_old_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_07_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_07_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_07_rich_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_08_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_08_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_08_basic_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_08_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_08_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_08_old_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_08_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_08_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_08_rich_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_09_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_09_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_09_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_09_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_09_old_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_09_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_09_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_10_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_10_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_10_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_10_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_10_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_10_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_11_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_11_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_11_basic_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_11_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_11_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_11_old_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_11_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_11_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_11_rich_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_12_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_12_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_12_basic_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_12_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_12_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_12_old_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_12_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_12_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_12_rich_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_13_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_13_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_13_basic_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_13_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_13_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_13_old_03": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_13_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_13_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_14_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_14_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_14_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_14_old_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_14_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_14_rich_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_15_basic_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_15_basic_02": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_15_old_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.Pants_15_rich_01": return CRStockProtectionCatalog.Profile(2);
      case t"Items.TShirt_01_basic_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_01_basic_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_01_basic_03": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_01_old_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_01_old_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_01_old_03": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_01_rich_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_01_rich_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_01_rich_03": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_basic_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_basic_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_basic_03": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_basic_04": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_basic_05": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_old_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_old_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_old_03": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_old_04": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_rich_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_rich_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_rich_03": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_02_rich_04": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_03_basic_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_03_basic_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_03_basic_03": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_03_old_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_03_old_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_03_old_03": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_03_rich_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_03_rich_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_03_rich_03": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_04_old_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_04_old_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_04_old_03": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_04_old_04": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_04_old_05": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_04_old_06": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_05_old_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_05_old_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_05_old_03": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_05_old_04": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_05_old_05": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_05_old_06": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_06_basic_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_06_basic_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_06_old_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_06_old_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_06_rich_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_06_rich_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_07_basic_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_07_basic_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_07_old_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_07_old_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_07_rich_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_07_rich_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_08_basic_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_08_basic_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_08_old_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_08_old_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_08_rich_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_08_rich_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_09_basic_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_09_basic_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_09_old_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_09_old_02": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_10_basic_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_10_old_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_10_rich_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_11_basic_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_11_old_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.TShirt_11_rich_01": return CRStockProtectionCatalog.Profile(1);
      case t"Items.Vest_01_basic_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_01_basic_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_01_old_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_01_old_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_01_rich_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_01_rich_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_02_basic_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_02_basic_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_02_old_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_02_old_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_02_rich_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_02_rich_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_03_basic_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_03_basic_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_03_old_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_03_old_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_03_rich_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_03_rich_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_04_basic_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_04_basic_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_04_old_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_04_old_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_04_rich_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_04_rich_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_13_basic_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_13_basic_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_13_rich_01": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_13_rich_02": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_13_rich_03": return CRStockProtectionCatalog.Profile(3);
      case t"Items.Vest_13_rich_04": return CRStockProtectionCatalog.Profile(3);
    }
    return CRStockProtectionCatalog.Profile(0);
  }
}
